# -Wno-c++17-extensions: Clang complains about nodiscard if the standard is not set to c++17.

name: Linux Clang

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-clang
  cancel-in-progress: true

jobs:
  # Build ExaEpi
  build_clang_single:
    name: Clang@7.0 C++17 SP NOMPI Debug [lib]
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -Wnon-virtual-dtor -Wno-unused-parameter"}
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_clang7.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                      \
            -DCMAKE_BUILD_TYPE=Debug                  \
            -DCMAKE_VERBOSE_MAKEFILE=ON               \
            -DAMReX_MPI=OFF                           \
            -DAMReX_PRECISION=SINGLE                  \
            -DAMReX_PARTICLES_PRECISION=SINGLE        \
            -DCMAKE_C_COMPILER=$(which clang)         \
            -DCMAKE_CXX_COMPILER=$(which clang++)
        make -j 2

  build_clang_mixed:
    name: Clang@7.0 C++17 SP Particles DP Mesh Debug
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -O1 -Wnon-virtual-dtor -Wno-unused-parameter"}
      # It's too slow with -O0
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_clang7.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                      \
            -DCMAKE_BUILD_TYPE=Debug                  \
            -DCMAKE_VERBOSE_MAKEFILE=ON               \
            -DAMReX_PRECISION=DOUBLE                  \
            -DAMReX_MPI=OFF                           \
            -DAMReX_PARTICLES_PRECISION=SINGLE        \
            -DCMAKE_C_COMPILER=$(which clang)         \
            -DCMAKE_CXX_COMPILER=$(which clang++)
        make -j 2

  build_clang_double:
    name: Clang@7.0 C++17 DP Particles DP Mesh Debug
    runs-on: ubuntu-20.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -O1 -Wnon-virtual-dtor -Wno-unused-parameter"}
      # It's too slow with -O0
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_clang7.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                      \
            -DCMAKE_BUILD_TYPE=Debug                  \
            -DCMAKE_VERBOSE_MAKEFILE=ON               \
            -DAMReX_MPI=OFF                           \
            -DCMAKE_C_COMPILER=$(which clang)         \
            -DCMAKE_CXX_COMPILER=$(which clang++)
        make -j 2
